from __future__ import annotations

from core.domain_interface import DomainsInterface, domain_interfaces
from core.model import Model
from core.sdf import Box, Difference, Sphere
from core.sdf.roles import Domain, DomainKind


def _fluid(name: str, region) -> Domain:
    return Domain(name=name, kind=DomainKind.FLUID, region=region)


def _solid(name: str, region) -> Domain:
    return Domain(name=name, kind=DomainKind.SOLID, region=region)


def _pipeline_model() -> tuple[Model, Sphere, Box]:
    """A pipeline-like model where solids are shared between Domains:

    bore (id 1)        -> the gas Domain's region, and the obstacle subtracted
                          from the steel Domain  -> gas<->pipe interface.
    pipe_outer (id 2)  -> the steel Domain's outer wall, and the obstacle
                          subtracted from the sea -> pipe<->sea interface.
    """
    bore = Sphere(name="bore", object_id=1, radius=0.3)
    pipe_outer = Box(name="pipe_outer", object_id=2, half_size=(0.5, 0.5, 2.0))
    sea_box = Box(name="sea_box", object_id=3, half_size=(2.0, 2.0, 3.0))

    gas = _fluid("gas", bore)
    pipe = _solid(
        "pipe", Difference(name="shell", object_id=4, left=pipe_outer, right=bore)
    )
    sea = _fluid(
        "sea", Difference(name="water", object_id=5, left=sea_box, right=pipe_outer)
    )
    return Model(domains=(gas, pipe, sea)), bore, pipe_outer


def test_finds_both_shared_interfaces() -> None:
    model, _, _ = _pipeline_model()
    interfaces = domain_interfaces(model)
    pairs = {(i.domain_a, i.domain_b) for i in interfaces}
    assert pairs == {("gas", "pipe"), ("pipe", "sea")}


def test_interface_retains_generating_node_and_owner() -> None:
    model, bore, pipe_outer = _pipeline_model()
    by_owner = {i.owner_object_id: i for i in domain_interfaces(model)}
    # gas<->pipe interface is generated by the shared bore primitive.
    assert by_owner[1].generating_node is bore
    assert {by_owner[1].domain_a, by_owner[1].domain_b} == {"gas", "pipe"}
    # pipe<->sea interface is generated by the shared pipe_outer primitive.
    assert by_owner[2].generating_node is pipe_outer
    assert {by_owner[2].domain_a, by_owner[2].domain_b} == {"pipe", "sea"}


def test_non_adjacent_domains_have_no_interface() -> None:
    # gas and sea share no primitive (the steel wall separates them).
    model, _, _ = _pipeline_model()
    pairs = {(i.domain_a, i.domain_b) for i in domain_interfaces(model)}
    assert ("gas", "sea") not in pairs


def test_disjoint_domains_with_no_shared_solid_have_no_interfaces() -> None:
    a = _fluid("a", Sphere(name="a", object_id=1, radius=0.4))
    b = _fluid("b", Sphere(name="b", object_id=2, center=(5, 0, 0), radius=0.4))
    assert domain_interfaces(Model(domains=(a, b))) == ()


def test_interface_pair_names_are_sorted_deterministic() -> None:
    model, _, _ = _pipeline_model()
    for i in domain_interfaces(model):
        assert i.domain_a <= i.domain_b
