from __future__ import annotations

from PySide6.QtCore import QObject, Signal


class AppSignals(QObject):
    document_changed = Signal(object)
    scene_changed = Signal(object)
    node_selected = Signal(object)
    selection_changed = Signal(object)
    add_primitive_requested = Signal(str)
    viewport_create_requested = Signal(str)
    viewport_shape_drawn = Signal(str, object, object, object)
    viewport_shape_preview_requested = Signal(str, object, object, object)
    viewport_point_shape_drawn = Signal(str, object, str)
    viewport_move_tool_requested = Signal()
    viewport_boundary_tool_requested = Signal()
    viewport_move_requested = Signal(int, object)
    viewport_move_preview_requested = Signal(int, object)
    viewport_rotate_tool_requested = Signal()
    viewport_rotate_requested = Signal(int, str, float, object)
    viewport_rotate_preview_requested = Signal(int, str, float, object)
    viewport_transform_requested = Signal(int, object, object)
    viewport_extrude_requested = Signal(int, float)
    viewport_extrude_preview_requested = Signal(int, float)
    viewport_revolve_requested = Signal(int, str, object, object, object, float)
    viewport_revolve_preview_requested = Signal(int, str, object, object, object, float)
    viewport_frame_requested = Signal()
    viewport_scene_object_selected = Signal(int)
    viewport_boundary_hovered = Signal(object)
    viewport_boundary_region_requested = Signal(object)
    delete_nodes_requested = Signal(object)
    sdf_op_requested = Signal(str, object)
    sdf_op_preview_requested = Signal(str, object)
    transform_requested = Signal(str, object)
    solid_from_2d_requested = Signal(str, object)
    set_domain_requested = Signal(object, str)
    unset_domain_requested = Signal(object)
    set_fluid_root_requested = Signal(object)
    set_tag_enabled_requested = Signal(object, bool)
    create_boundary_region_requested = Signal(object)
    create_polygon_from_polyline_requested = Signal(object)
    undo_snapshot_ready = Signal(object)
    working_unit_changed = Signal(object)
    node_edited = Signal()
    log_message = Signal(str, str)


signals = AppSignals()
